### ISSUE TITLE
Add fmap and Sidecar Changes to Documentation on DICOMtoBIDS conversion

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#113]
In the DICOM to BIDS Conversion documentation showing the example conversion_config.json, can that include example sections for designating fmap images to assign to specific functional scans? Including how to write BIDS-acceptable "customLabels" for them

And in that same section, can there be an example/description of adding "SidecarChanges: {TaskName: "[task name from custom label]"}" to functional scan sections on the conversion_config.json? Not designating "Task Names" was an error that popped up in our BIDS Validator output for all of our functional scans when we didn't have this SidecarChanges line.

Thank you!

**Comment by trh3** [comment]
Hello! Great idea, thank you for suggesting it! I have added in documentation to show how to designate the fieldmaps, and link them to functional scans. Now, this is a fairly complex task, given the variety of fieldmaps possible, so I suggest following the link to the BIDS specification I included to see how to format your specific type of fieldmap.
