### ISSUE TITLE
"SidecarChanges" not working in convert2bids command

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#114]
The BIDS validator was giving us the error "You have to define 'TaskName' for this file" for all 6 of our functional scans (3 tasks, each acquired in both AP and PA directions). We tried to address this by adding  "SidecarChanges": {"TaskName" : "<task name>"} to each functional scan in our conversion_config.json

We've tried multiple iterations of  our task names (see conversion_config_AP.json attached 
[conversion_config_AP.pdf](https://github.com/cohenlabUNC/clpipe/files/4996360/conversion_config_AP.pdf)
) but the validator is still showing an error (see BIDS validator output attached 
[Output-BIDSValidator-jobid-65139645.pdf](https://github.com/cohenlabUNC/clpipe/files/4996369/Output-BIDSValidator-jobid-65139645.pdf)
). I checked the tasks' sidecar .json files and found that a TaskName had not been added to that file after running convert2bids, which explains the validator errors (see the attached sidecar .json for our REW task 
[sub-1068_task-REW_acq-AP1_bold.pdf](https://github.com/cohenlabUNC/clpipe/files/4996381/sub-1068_task-REW_acq-AP1_bold.pdf)
).

Do you know why the command "SidecarChanges" isn't actually working to edit our sidecar .json files? Is it a formatting issue in our conversion_config file, or maybe something else?

**Comment by trh3** [comment]
Ah, fortunately this is a simple fix! The command is "sidecarChanges:" rather than "SidecarChanges:"

**Comment by amandam1510** [comment]
Wow I'm glad it was such a simple fix! After that edit, everything is working and the BIDS Validation was successful! Thank you!

**Comment by trh3** [comment]
Glad to hear!
