### ISSUE TITLE
fmapcleanup clarification

### ISSUE THREAD

**Issue by macmitch** [cohenlabUNC/clpipe#120]
Hey Teague,
I would like to request that documentation be added to the readthedocs regarding the `fmapcleanup` field. It looks like the default is `3` but in my clpipe_config.json you had set the field to `-1`. I think the `fmapcleanup` field specifies how many volumes to use in the distortion correction, but I am not sure that is correct. My guess is that `-1` means this feature is turned off because we are not collecting fieldmaps. However, I would like to request that you add some explanation about possible values to be in this field and what they mean.
Thanks! Mackenzie

**Comment by trh3** [comment]
Thanks for catching this, I will definitely add this to the documentation right away.

**Comment by trh3** [comment]
Updated documentation.
