### ISSUE TITLE
Updating clpipe version (and fMRIPrep version), add to documentation

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#122]
I'm not sure how to check our clpipe version, but I think it's from before the GLM component was incorporated. I realized this when I tried running glm_setup on a subject and got a weird traceback message (pictured below). How can I install the latest version of clpipe (if it's any different from initial installation), and will this process affect any of the directories and files that were already created using the first version? Can this process also be described in the documentation?

<img width="1256" alt="Screen Shot 2020-08-16 at 8 40 39 PM" src="https://user-images.githubusercontent.com/68916720/90347849-c0f31780-e000-11ea-8647-d5ac9f21b310.png">

Along the same lines, does the newest version of clpipe include an fMRIPrep update? The one our clpipe version currently uses is v1.5.0, and our fMRIPrep logs all display a concerning message that this version was flagged for significant issues. One of those issues was discussed here: https://github.com/poldracklab/fmriprep/issues/1819 and it seems pretty similar to the errors shown for some of our subjects who failed fmriprep. It looks like a new major release 20.0.0+ came out right before the pandemic in Feb. But I'm not sure if that is in the works to be implemented in clpipe or not

**Comment by trh3** [comment]
Hi! 

The error you are seeing is due to a discrepancy between numpy and scipy. I've updated clpipe to use versions of both that should work together (this update was 14 days ago). To get that update, you should just reinstall clpipe:

`pip install --user --upgrade git+git://github.com/cohenlabUNC/clpipe`

As for updating fmriprep, this is a bit more of a difficult thing to do. Chiefly because one needs to generate a new singularity image, and upload it to longleaf, which must be done through a linux machine, and cannot be done directly on Longleaf. I should have some time later this week to create a copy, and I will let you know when that occurs. As I recall, I previously updated fmriprep to 1.5.3. If you go to the singularity_imgs folder in the hng group, you can see a list of all the fmriprep versions I have uploaded. Pick the most recently numbered one, and change your fmripreppath option in the configuration file to match.

**Comment by amandam1510** [comment]
Thank you for the info Teague! I'll reinstall clpipe asap

Regarding fmriprep, that's helpful to know about what all goes into an update for that! Some of our bug errors may resolve with the 1.5.3 version (fingers crossed). For the singularity image, it looks like you've uploaded one for the 20.0.7 version of fmriprep. Should I use that file as the most recently numbered one, even though it doesn't match the 1.5.3 version currently in clpipe?

**Comment by trh3** [comment]
Yes, you should use the 20.0.7. Clpipe is, at least when it comes to fmriprep, basically a convenience wrapper. so when you change your fmripreppath in the config, it just uses that version of fmriprep. Shouldn't cause any issues, just make sure that all of your data is processed with a single version of fmriprep

**Comment by amandam1510** [comment]
That's super helpful, thank you! I never knew that the singularity image would dictate the version of fMRIPrep that's launched! I'll definitely make a note of this

**Comment by amandam1510** [comment]
So I reinstalled clpipe using the above command, and then logged back into Longleaf. But running "glm_setup --help" gives me the same numpy traceback message as above. After checking the installation documentation, I'm wondering if I should have used "pip3" instead of "pip" at the beginning of the command?

**Comment by trh3** [comment]
Yes, try that actually

**Comment by amandam1510** [comment]
Ok I tried that and these are installation log message that came up. I tried "glm_setup --help" after the installation finished & after logging back into Longleaf, and both times it still displayed the numpy traceback. Could it be an issue of the package not actually installing correctly since it keeps saying upgrades are being skipped (possibly due to my permissions since I'm not the owner of our server space, though our grad student was able to do the initial installation successfully)?

<img width="1400" alt="Screen Shot 2020-08-17 at 12 48 45 PM" src="https://user-images.githubusercontent.com/68916720/90421850-027ad580-e088-11ea-8c90-5ae396b6f85c.png">
<img width="1391" alt="Screen Shot 2020-08-17 at 12 49 24 PM" src="https://user-images.githubusercontent.com/68916720/90421899-16263c00-e088-11ea-8c3a-8df9f6d8e820.png">
<img width="1379" alt="Screen Shot 2020-08-17 at 12 49 57 PM" src="https://user-images.githubusercontent.com/68916720/90421961-2a6a3900-e088-11ea-84f3-08013a0718d3.png">
<img width="1383" alt="Screen Shot 2020-08-17 at 12 50 25 PM" src="https://user-images.githubusercontent.com/68916720/90422003-3a821880-e088-11ea-80df-3bd08a0e3c84.png">

**Comment by trh3** [comment]
Oh, I think I know what this is. The glm_setup function calls the Longleaf installation of FSL. That then calls the incorrect versions of numpy and scipy. Could you let me know what this returns:

`echo $PYTHONPATH`

**Comment by amandam1510** [comment]
It returns this:
/nas/longleaf/apps/python/3.6.6/lib/python3.6:/nas/longleaf/apps/python/3.6.6/lib/python3.6/site-packages

**Comment by trh3** [comment]
Alright, so you are going to want to go to your home folder and open up your .bash_profile, using vim. Then add at the bottom the following:

`export PYTHONPATH="/nas/longleaf/home/amandanm/.local/lib/python3.6/site-packages:$(PYTHONPATH)"`

That should force python to preferentially use the libraries in the user directory. Remember to relogin after you change your .bash_profile

**Comment by amandam1510** [comment]
Okay I added that phrase, and then logged back in. Then I re-ran glm_setup --help, and it gave me the same traceback.

My bash profile:
<img width="877" alt="Screen Shot 2020-08-17 at 1 47 43 PM" src="https://user-images.githubusercontent.com/68916720/90427208-3bb74380-e090-11ea-95dc-2b9e957bb4fc.png">

A message about Python when opening Terminal after logging back in:
<img width="768" alt="Screen Shot 2020-08-17 at 1 46 36 PM" src="https://user-images.githubusercontent.com/68916720/90427097-1591a380-e090-11ea-9bc5-714858d08e73.png">

**Comment by trh3** [comment]
My mistake, it should be:

export PYTHONPATH="/nas/longleaf/home/amandanm/.local/lib/python3.6/site-packages:${PYTHONPATH}"

**Comment by amandam1510** [comment]
Okay, I'll add that! Should it go under #bash profile or #User specific environment, or does it not matter?

**Comment by trh3** [comment]
It should go at the very end of the file, just to make sure it takes precedent

**Comment by amandam1510** [comment]
I think I did it correctly, and my terminal opened without showing pythonpath wasn't found. But glm_setup didn't work. Here's a new pic of my bash profile (sorry for all the messages, I'm not familiar with editing my profile). I'm not sure if the export phrase is far enough down.

<img width="1240" alt="Screen Shot 2020-08-17 at 2 05 30 PM" src="https://user-images.githubusercontent.com/68916720/90428916-b84b2180-e092-11ea-8256-dd2b76eff5c3.png">

**Comment by trh3** [comment]
Alright, I managed to solve it. Go ahead and completely remove that PYTHONPATH line from your bash_profile, then reinstall clpipe. It should now use the correct version of nibabel.

**Comment by amandam1510** [comment]
Awesome, I can use the glm commands now! Thank you so much for your help Teague!!
