### ISSUE TITLE
glm_setup: Reference Image vs. Brain Mask

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#123]
Hi Teague! submitting this new issue since it's a separate topic

In the glm_setup section of our clpipe_glm_config.json, I wanted to clarify some questions about the Reference Image and the Brain Mask (with MaskFolderRoot and MaskSuffix). Our standard space is the MNIPediatricAsym from cohort 2. After looking through hng's image files in singularity_imgs/template_flow, I've only found one image with the "desc_fMRIPrep_boldref" suffix, and it's for MNI152NLin2009cAsym. Is this still the file we should be using as our "ReferenceImage", and then use each subject's newly-created brain mask file from data_fmriprep as our brain mask? After reading the documentation, it's still a little unclear to me if we can use the MNI152 as the reference image if it's determining our dimensions and resolution, since it's presumably a larger brain than the pediatric one.

(Also please let me know if I should be submitting more "user questions" like this in another place other than Issues!)

**Comment by trh3** [comment]
There should be a boldref type image in the MNIPediatricAsym folder, though it might not be called desc_fMRIPrep. If you show me a screenshot of what is in the MNIPediatricAsym folder, I can tell you which file to use.

For the MaskFolderRoot, that should be the fmriprep directory, and the brain mask you want to use is the one for the MNIPediatricAsym, that should be in your fmriprep output per subject (if I recall correctly).

And this is a fine place to submit these questions, that way if anybody else runs into something similar, there will be a record. I also see them immediately, which makes it easy to respond.

**Comment by amandam1510** [comment]
Here's a screenshot. Could it maybe be the files with the PD or T1w/T2w suffix?
<img width="635" alt="Screen Shot 2020-08-17 at 12 16 37 PM" src="https://user-images.githubusercontent.com/68916720/90418719-81b9da80-e083-11ea-8c61-908b6f192516.png">

Okay, our MaskFolderRoot and MaskSuffix sounds like we've formatted them correctly then, since we're pointing to the file named "space_MNIPediatricAsym_desc-brain_mask" in each of our subjects' fmriprep directories.

**Comment by trh3** [comment]
Yup, its going to be the T1w. I would suggest the res-2 version (which is just the resolution in mm of the isomorphic voxels). To go into a bit more depth, FSL's GLM requires a reference image (which it typically registers the functional images to), even if that isn't ever used in the model itself. The functional images are required to have identical dimensions and resolutions, so the glm_setup function does the necessary work of putting the functional images into the correct dimensions, and resamples them into the correct resolution. This means that when your GLMs are done running, you can overlay your various maps on the reference image you specified. All this is just a workaround for FSL's very finicky setup.

**Comment by amandam1510** [comment]
Gotcha, and I'll use res-2. That was a helpful explanation of how the reference image is used, thank you!
