### ISSUE TITLE
glm_setup not working, may be nipype issue

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#124]
Hi! I've tried running one participant through glm_setp for one task ~5pm yesterday (after the clpipe reinstall), and the log output file has only shown "INFO:root:Running Subject 1044” the entire time, while our directory for the resulting image files and confounds.tsv is still empty. The slurm info on this batch job says it completed in 10 seconds. I tried running the command again with the option "-debug" and the log shows this

<img width="1039" alt="Screen Shot 2020-08-18 at 1 26 11 PM" src="https://user-images.githubusercontent.com/68916720/90545272-6370df00-e156-11ea-985d-123e8352c41b.png">

So it looks like it may be a Nipype problem?

**Comment by amandam1510** [comment]
This error was not due to a clpipe programming bug, but rather a naming mismatch between how our task was named in our conversion_config file (next to customLabel) and what we put for TaskName in our glm_config file!

**Comment by trh3** [comment]
Indeed! I am planning on adding more informative messages when the software doesn't detect any scans, but until I do, if the pipeline quits without error or other messages, it is likely due to a naming mismatch somewhere in the configuration files
