### ISSUE TITLE
get_config_file or grab_config_file

### ISSUE THREAD

**Issue by macmitch** [cohenlabUNC/clpipe#125]
Hey Teague, The documentation currently specifies `grab_config_file`. This is not currently working on the most recent version of the pipeline. I recommended that Andrea use `get_config_file` as that is what I have used on previous versions of the pipeline. Is `get_config_file` going to be updated to `grab_config_file` or is this a typo in the readthedocs? Thanks! Mackenzie

**Comment by trh3** [comment]
Yup, typo, fixed now!
