### ISSUE TITLE
fMRIPrep default version in clpipe_config.json

### ISSUE THREAD

**Issue by macmitch** [cohenlabUNC/clpipe#128]
Hi Teague, I wanted to ask if you were planning to update the default version of fMRIPrep that is prepopulated in the clpipe_config.json files to be the stable version of fMRIPrep. This came up in trainings and I wanted to ask! I think this would be a useful edit if you dont have other concerns with updating it!
Mackenzie

**Comment by trh3** [comment]
Just uploaded that, and updated the default!

**Comment by macmitch** [comment]
Thanks, Teague! It looks like the newest fMRIPrep singularity image seems to not be executable by anyone in the hng group so fmriprep is failing and throwing this error: "could not open image /proj/hng/singularity_imgs/fmriprep-version-20.2.1.simg: failed to retrieve path for /proj/hng/singularity_imgs/fmriprep-version-20.2.1.simg: lstat /proj/hng/singularity_imgs/fmriprep-version-20.2.1.simg: no such file or directory"
Please update the permissions on this file when you have a chance (and it looks like some others in that directory arent executable by HNG POSIX members either - I am not sure if that is purposeful or not). Thank you!

**Comment by trh3** [comment]
I just updated the permissions. Could you check to make sure it works and let me know?

**Comment by hlmorgan8** [comment]
Hi Teague! I think I am running into an issue with permissions and the fmriprep-version-20.2.1.smg as well. I just tried to run fMRIPrep today and got this error with each one of my subjects: 

PermissionError: [Errno 13] Permission denied: '/proj/hng/singularity_imgs/template_flow/tpl-WHS/tpl-WHS_res-2_desc-BrainCerebellumExtraction_mask.nii.gz'

When I used version fmriprep_1.5.3.sif recently, it worked just fine. Thank you in advance and please let me know if I should post this error somewhere else!

**Comment by trh3** [comment]
Hello! It looks like that specific folder was created by somebody else, likely Cleanthis? He would need to change the permissions there

**Comment by wasciutto** [comment]
Closing issue for now - feel free to reopen if this problem is persisting
