### ISSUE TITLE
fMRIPrepPath brain atlas permissions error (fMRIPrep v20.2.1) 

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#131]
Hi Teague! We tried to run fMRIPrep version 20.2.1 on a subject via clpipe, and the job failed due to a permissions error. The weird thing is that in our fMRIPrepOptions in our config file, our chosen atlas is the MNIPediatricAsym, cohort 2. Our config file is below, and everything is the same as when we submitted it except the FMRIPrepPath pointed to "fmriprep-20.2.1.simg".

<img width="825" alt="Screen Shot 2020-12-17 at 9 40 51 AM" src="https://user-images.githubusercontent.com/68916720/102501909-f578ed80-404b-11eb-9c0c-3ba561b62495.png">

But the "permissions denied" error was for a file in the WHS atlas directory, which we don't specify using anywhere in our config file.

<img width="1351" alt="Screen Shot 2020-12-17 at 9 45 14 AM" src="https://user-images.githubusercontent.com/68916720/102502413-923b8b00-404c-11eb-883d-c4ac44885554.png">

We are now running the same subject with fMRIPrep version 20.0.7 and it's running successfully, so I wonder if the issue is with v20.2.1? Any help would be much appreciated!

--Amanda (CIRCLE Lab with Dr. Sheridan at UNC)

**Comment by amandam1510** [comment]
Just checked and it looks like this is the same issue Hannah ran into with v20.2.1 from Issue #128, and she may not have been using the WHS atlas either!

**Comment by trh3** [comment]
Hello! It appears that WHS is a supplementary atlas that helps with brain segmentation, It appears that this atlas was originally created with a bad permissions structure. I've sent an email to the person who owns the files (the original creator), and once they change the permissions, this error should stop.

**Comment by hlmorgan8** [comment]
Hi both, it seems like I am also running into the same issue. I got 30 minutes into running fmriprep and got this error. Let me know if you need any more information! 

201217-13:43:09,930 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_01_wf.anat_preproc_wf.brain_extraction_wf.mrg_tmpl
201217-13:43:09,952 nipype.workflow CRITICAL:
	 fMRIPrep failed: Workflow did not execute cleanly. Check log for details

**Comment by wasciutto** [comment]
Closing issue for now - feel free to reopen if this problem is persisting
