### ISSUE TITLE
Fieldmap intendedfor error with newer version of pipeline?

### ISSUE THREAD

**Issue by macwoodburn** [cohenlabUNC/clpipe#132]
I am rerunning analyses with a newer version of fmriprep (previously 'fmriprep_1.5.0.sif', now using 'fmriprep-version-20.0.7.simg' per a superuser recommendation). When I try to run "fmriprep_process -config_file /proj/cohenlab/projects/MAP/clpipe_config_map_012021.json -submit 0011", the job quits bc of a bids validator error that I have had with the previous version of fmriprep:
![image](https://user-images.githubusercontent.com/34429310/104363672-89bb6080-54e3-11eb-96e3-fa5f02944d85.png)

I remember this having to be fixed to allow the fieldmap IntendedFor line be more flexible to file name types. Is this the same issue again with this newer version of the pipeline?

Thanks,
Mac

**Comment by wasciutto** [comment]
Closing as this is not an issue with clpipe, but with conforming to the BIDS standard
