### ISSUE TITLE
Error with convert2bids procedure

### ISSUE THREAD

**Issue by SR-Walton** [cohenlabUNC/clpipe#134]
Hello, I am new to neuroimaging (and linux) and my colleague and I are trying to set up directories in the BIDS format through clpipe. When running the convert2bids command, we're encountering the following error: " 'NoneType' object is not subscriptable." 
![Screen Shot 2021-02-05 at 2 03 17 PM](https://user-images.githubusercontent.com/78805420/107377309-d0878080-6ab8-11eb-9dd9-33d8f5b67614.png)

However, we have had success using the helper to identify image types from DICOMS; and we've subsequently been able to update the configuration file. 

I'm not sure if it's related, but there also appeared to be a python error during installation of clpipe, though the requisite directories and files appeared as we expected. In using the suggested command from the warning message to upgrade the pip version (see image below), we are met with the exact same warning message about the pip versions. In other words, version 20.0.2 doesn't appear to upgrade to 21.0.1 using this command, and using the command to upgrade just repeats the warning message. 

![Screen Shot 2021-02-05 at 2 04 49 PM](https://user-images.githubusercontent.com/78805420/107378597-1f81e580-6aba-11eb-85f4-37ca96e2bf18.png)

We would appreciate any help you can provide! Thank you very much in advance!

-Sam

**Comment by trh3** [comment]
Hello!

This error can occur when the DICOM format string is not constructed correctly, which is always a bit of a tricky proposition. Could you let me know what your "DICOMFormatString" is from the clpipe configuration file, and what the folder structure is for your DICOM storage (i.e. is it, /dicoms/sub-<subid>/ or /dicoms/<subid>/, etc... etc...). 

What is actually happening is that the sub_list object, which should have all subject folders in it, is empty, which can only occur when 1) the DICOM format string is wrong, or 2) the configuration file doesn't point towards the right folder. So this should be a fairly simple fix.

As for errors, I haven't seen that one before. It shouldn't be a problem, but I will take a look at it. The PIP warning is also just fine, that is something that can only be handled by the longleaf IT staff, and it doesn't make a difference either way.

**Comment by SR-Walton** [comment]
Hello Teague, thank you for the quick reply! The DICOMFormatString is "{subject}/SCANS/*/", and the folder structure is "/raw_dicoms/{subject}/SCANS/[then a directory for each run]/DICOM/". This is the format in which the data were sent to us, and I think I can see where the disconnect may be now. In this case, should the DICOMFormatString be "{subject}/SCANS/*/DICOM/"?

Thank you also for your feedback on the PIP warning. We'll not worry about it for now. 

Please let me know if I can supply any more helpful information. 

Thank you very much! -Sam

**Comment by trh3** [comment]
Yes, that looks about correct. One way of testing this is to use the convert2bids command without the -submit, or the -subject. That will print out the commands to the terminal, without submitting them. If you run convert2bids like this, and nothing is printed to the terminal, or an error is thrown, then the DICOMFormatString is bad. Let me know if the change worked, else we can keep troubleshooting!

**Comment by SR-Walton** [comment]
I edited the clpipe_config.json file with the new DICOMFormatString as above, and after running the convert2bids without -submit or -subject, a 'NoneType' error occurred again, but it looked a little different at the end this time: 

![clpipe error 2 10 21](https://user-images.githubusercontent.com/78805420/107548037-297c1500-6b9c-11eb-8fa0-8c24cdc5988c.png)

Looks like there's still some troubleshooting to be done. Thank you so much for your patience in helping me figure this out!

**Comment by trh3** [comment]
Hmmmm, lets try the same DICOMFormatString, but just drop that final / after the DICOM

**Comment by SR-Walton** [comment]
Unfortunately, that also didn't work. I received the same error again.

**Comment by SR-Walton** [comment]
Hello Teague -- I wanted to follow up to let you know that I tried another couple of options with no further success. Namely, I tried using a wildcard instead of "{subject}" in the DICOMFormatString, both with and without the ending "/". 
Do you have any other thoughts on how to troubleshoot this issue? If it would be easier to meet synchronously to work through ideas, please feel free to email me at srwalton@email.unc.edu and we can schedule something that works for your schedule. Thank you very much. -Sam

**Comment by trh3** [comment]
Yes, let's set up a meeting time, I'll send you an email!

**Comment by macwoodburn** [comment]
@trh3 @SR-Walton I am getting this same exact error when trying to convert a new subject for my study. I have been able to succesfully convert subjects prior with convert2bids but am getting this error now... Did you both find a solution to this error?

**Comment by trh3** [comment]
@macwoodburn In troubleshooting this, I made a modification to the convert2bids function. If you have a trailing / in your DICOMFormatString, try removing it and seeing if it finds the subjects

**Comment by macwoodburn** [comment]
ahah! this is working! my convert2bids job is now running! thanks Teague!
