### ISSUE TITLE
Partition error for clpipe commands

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#135]
Hi Teague!

I reinstalled clpipe on Friday after Mackenzie let everyone know of the updates to the clpipe launch scripts with respect to UNC's Longleaf partitions. After logging out and then back in, I'm still running into the error below when I try to submit a subject for preprocessing:

<img width="870" alt="Screen Shot 2021-02-21 at 9 53 36 AM" src="https://user-images.githubusercontent.com/68916720/108628766-acb62a00-742a-11eb-9a99-f5e9f53bcf99.png">

It looks like "qos specification" points to a partition issue remaining in the clpipe scripts. Let me know if you want me to try anything else!

**Comment by trh3** [comment]
It appears as though Longleaf ITS needs to grant access to that partition. Send an email to research computing asking for access to the snp partition.
