### ISSUE TITLE
Default Sphere Size - ROI Extraction Question

### ISSUE THREAD

**Issue by hlmorgan8** [cohenlabUNC/clpipe#136]
Hellow! I was wondering if there is information about the default size of the spheres of the atlases in the documentation? For example, I left the -radius tag out of my command line (see below) but did not specify a radius size in my configuration file (see ROI Extraction Option below). Everything ran fine but I am wondering what radius sphere size was used.

Command Line:
fmri_roi_extraction -config_file clpipe_config.json -task rest -atlas_name power -submit

Config File Section - ROI Extraction
"ROIExtractionOptions": {
		"TargetDirectory": ".../data_postproc/postproc_default",
		"TargetSuffix": "postproc_noScrubGSR.nii.gz",
		"OutputDirectory": "..../postproc_noScrubGSR",
		"Atlases": [
			"power"
		],
		"RequireMask": true,
		"PropVoxels": 0,
		"MemoryUsage": "8000",
		"TimeUsage": "2:0:0",
		"NThreads": "1",
		"LogDirectory": ".../logs/ROI_extraction_logs"
	},

Thank you!

-Hannah Morgan

**Comment by trh3** [comment]
Ahhhh, good catch. The default radius is 5mm, which is specified in the docstring of the function (what  you get when you --help), but it should be specifiable in the config file. I'll make that change ASAP.

**Comment by hlmorgan8** [comment]
Thank you, Teague! I didn't see it when I used --help but I must have missed it.

**Comment by wasciutto** [comment]
Opening issue to add this to config as #199
