### ISSUE TITLE
Configuration File Documentation Question

### ISSUE THREAD

**Issue by hlmorgan8** [cohenlabUNC/clpipe#137]
Hi Teague! 

Apologies for another post but I was hoping for some clarification on the documentation in the configuration file (here: https://clpipe.readthedocs.io/en/latest/configfiles.html)  

For context, I was looking for more information concerning Spectral Interpolation and PropVoxel. I noticed that some of the field explanations say something like: "For more information on spectral interpolation see Postprocessing/Spectral Interpolation." However, when going to the Postprocessing fMRI I can't find any further information (https://clpipe.readthedocs.io/en/latest/postprocessing.html#postprocessing-fmri). Am I going to the wrong section for more information? 

Additionally, some of the field explanations are missing (e.g. PropVoxel) from the configuration file documentation. Is there somewhere else that I can find this information? 

Apologies if this will all be updated soon, I know there have been a few updates to the config files! 

-Hannah Morgan

**Comment by trh3** [comment]
Yes, I have to update the documentation quite a bit actually. 

Send me an email with any questions you have about Spectral interpolation, as that is its own kettle of fish. As for PropVoxel, that is a parameter setting how many voxels in an ROI need to be inside the brain mask for it to compute that ROI's timeseries. If there are ROIs that have less than the voxel proportion, they will be set to NA in the output.

**Comment by hlmorgan8** [comment]
Ok great, that's what I figured. And thank you for the PropVoxel explanation! I am sending you an email now about Spectral Interpolation :)
