### ISSUE TITLE
Error with glm_l2_preparefsf command

### ISSUE THREAD

**Issue by amandam1510** [cohenlabUNC/clpipe#140]
Hi Teague! We are currently preparing for Level 2 analysis, where we'll be combining L1 analyses from the AP sequence of our EmoReg task with the L1 of the PA sequence of the task. But we're running into issues using the glm_l2_preparefsf command. We're finding that if one user in our group ran a subject's Level 1 EmoReg_AP feat job, and a different user ran the Level 1 EmoReg_PA feat job, then the glm_l2_preparefsf command won't permit either user to create the Level 2 .fsf file for that subject. This error persists even after we've made sure that file permissions throughout both the L1 AP and L1 PA .feat directories are recursively set to chmod 775.

For example, my team member Lucy ran subject 1002's AP data through Level 1. I ran the subject's PA data through Level 1. Both Level 1 .feat directories have identical permissions, with full group permissions, but when I try to run the glm_l2_preparefsf command (just for this subject), I get the following error that I don't have permission to access one of the registration files in the AP data:
<img width="1362" alt="Screen Shot 2021-06-07 at 10 02 52 PM" src="https://user-images.githubusercontent.com/68916720/121110972-1d1b6800-c7dc-11eb-83f8-286287706ff8.png">
 
Even though the permissions on that file are full for the group:
<img width="819" alt="Screen Shot 2021-06-07 at 10 03 59 PM" src="https://user-images.githubusercontent.com/68916720/121111074-463bf880-c7dc-11eb-908c-57cd48a40146.png">

Lucy gets a reciprocal error, saying that she doesn't have permissions to the PA data (that I own, but she should have access to as a group member). When I run the clpipe command on another subject whose AP and PA data were both run through Level 1 analysis by me, it ends up working. 

We're not sure if this is a clpipe issue, or a deeper problem with file permissions either via FSL's FEAT programming or with Longleaf in general, but we figured we'd reach out to you first!

**Comment by trh3** [comment]
Hello! 

This is most likely a Linux permissions issue. Take a look at the .feat files and see if they are a) owned by the person you expected, and part of the group you expected. Different programs can lead to different permission sets that might lead to issues with the lack of Everybody write permissions. If you get me that info, I can help you from there!

**Comment by amandam1510** [comment]
I double checked the files you mentioned, and all the files and sub-directories in 1002's EmoReg_AP .feat files are owned by Lucy (Onyen "llurie") and belonging to our expected sheridanlab group with chmod 775/umask 002 permissions. For 1002's PA .feat files and sub-directories, they're all owned by me (owner's listed onyen is "amandanm") and also belong to our sheridanlab group with the same file permissions.

I've also verified with Research ITS that Lucy and I both belong to the sheridanlab group.

**Comment by wasciutto** [comment]
Closing due to this likely being a permissions issue not related to clpipe - happy to reinvestigate / reopen if needed
