### ISSUE TITLE
Extraction won't work with mask due to 'empty spheres'

### ISSUE THREAD

**Issue by wasciutto** [cohenlabUNC/clpipe#379]
What explains this error given when using roi extraction with a mask?

It comes out of the actual roi function as a ValueError:
```
WARNING: clpipe.roi_extraction - These spheres are empty: [  0   1   2   3   4   7   8   9  10  11  17  18  20  21  22  26  30  34
  36  37  49  52  74  75  77  80  82  86 101 102 105 113 115 118 119 120
 136 137 138 140 141 152 154 176 177 178 179 180 181 196 219 241 246 247
 248 249]
```

The original clpipe logic:https://github.com/cohenlabUNC/clpipe/blob/2f0a57be99153b99b3aa6916cd89a5935fdd4a0c/clpipe/roi_extractor.py#L199-L204 catches the ValueError and reruns without mask (and this happens even when a matching mask is found), so this seems expected/intentional.

What situation should allow for using roi extraction with a mask? What causes empty spheres?

**Comment by wasciutto** [comment]
Might have solved this - I think it's happening when any sphere are outside of the mask given

**Comment by wasciutto** [comment]
But now seeing that there is a separate output file that seems to be for ROIs that fall within the masked area specifically? That would contradict my above theory

**Comment by trh3** [comment]
This was a work around for nilearn's ROI extraction. If there are ROIs outside the mask, then the ROI extraction fails. The work around removes the use of the mask, and an additional output file that indicates what proportion of voxels are in vs outside of the mask is generated.

**Comment by wasciutto** [comment]
Explanation is much appreciate, Teague!
