### ISSUE TITLE
-TR flag not working from command line for fmri_postprocess

### ISSUE THREAD

**Issue by kaduffy** [cohenlabUNC/clpipe#53]
If specify the TR in the command line, receive an error (below). If the -TR flag is not used, it pulls it in from the file and runs successfully. 

Command line:
`fmri_postprocess -config_file /proj/cohenlab/projects/kki_adhd/scripts/GNGsConfig.json -task GNGs -TR 2.5 -log_output_dir /proj/cohenlab/projects/kki_adhd/clpipe_batchOutput_GNGs -submit 0905`

What is submitted to SLURM:
`sbatch -n 1 --mem=20000 --time=8:0:0 --cpus-per-task=1 --job-name="PostProcessing0905" --output=/proj/cohenlab/projects/kki_adhd/clpipe_batchOutput_GNGs/Output-PostProcessing0905.out --wrap="fmri_postprocess -config_file=/proj/cohenlab/projects/kki_adhd/data_BIDS/derivatives/fmriprep/GNGsConfig.json -target_dir=/proj/cohenlab/projects/kki_adhd/data_BIDS/derivatives/fmriprep/ -target_suffix=MNI152NLin2009cAsym_preproc.nii.gz -output_dir=/proj/cohenlab/projects/kki_adhd/data_BIDS/derivatives/fmriprep -output_suffix=clpipe_noscrub -log_output_dir=/proj/cohenlab/projects/kki_adhd/clpipe_batchOutput_GNGs -task=GNGs -tr=2.5  -single 0905"`

Error (in batchOutput log):
`Error: no such option: -t`

**Comment by wasciutto** [comment]
This has (finally) been fixed! #254
